# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the project into the image
ADD . /app

# Sync the project into a new environment, using the frozen lockfile
WORKDIR /app
RUN git clone https://github.com/freemocap/skellybot-analysis
RUN uv sync --frozen
ENV PYTHONPATH="${PYTHONPATH}:/app"


CMD ["uv", "run" ,  "skellybot_analysis/__main__.py"]
